import os
import sys
import pandas as pd
from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

um_score = config.get("um_score", 10)
df = pd.read_csv(config["tbl"], sep="\t")
df.asm = df.asm.map(os.path.abspath)

###################################################
# START reference alignment
###################################################
module reference_alignment:
    snakefile: "reference_alignment.smk"
    config: config

use rule * from reference_alignment as ra_*

###################################################
# END reference alignment
###################################################


rule all:
    input:
        ra = rules.ra_reference_alignment.input
